version: '3.8'

services:
  web:
    build: .
    command: gunicorn realface.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./logs:/var/log/realface
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    restart: always

  celery:
    build: .
    command: celery -A realface worker -l INFO
    volumes:
      - ./logs:/var/log/realface
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: