services:
  - type: web
    name: realface
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /data/media
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn realface.wsgi:application --worker-class=gthread --workers=1 --threads=2 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: realface.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: FERNET_KEY
        generateValue: true
      - key: SQLITE_PATH
        value: /data
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
    healthCheckPath: /health/
    healthCheckTimeout: 5
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1