# Generated by Django 5.1.2 on 2025-04-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_real', models.BooleanField(null=True)),
                ('confidence_score', models.FloatField(null=True)),
                ('analysis_result', models.TextField(null=True)),
            ],
        ),
    ]
