# Generated by Django 5.1.2 on 2025-04-26 04:18

import detector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to=detector.models.get_upload_path),
        ),
    ]
