# Generated by Django 5.1.2 on 2025-04-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_image_file_size_image_image_height_image_image_width_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
